services:
  redis-database-service:
    container_name: redis-database-service
    image: redis:latest
    ports:
      - "6379:6379"

  database-service:
    container_name: database-service
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookstore
    ports:
      - "3309:3306"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: database-service
    depends_on:
      - database-service
