services:
  redis-database-service:
    container_name: redis-database-service
    image: redis:latest
    ports:
      - "6379:6379"

  database-service:
    container_name: database-service
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookstore
    ports:
      - "3309:3306"
    volumes:
      - ./database:/var/lib/mysql
